### ISSUE TITLE
关于运行running报错的问题

### ISSUE THREAD

**Issue by XionghuiLi** [ViolinLee/18_dof_raspberry_pi_hexapod#3]
环境搭建和配置都解决了，WIFI可正常连接，蓝牙也已经连接配对，但运行running时会报大量的错，大多关于设备未连接、未发现设备等等，我觉得可能是没把主控板放到驱动板上，然后我把硬件什么的都做好，跑running依旧报跟之前一样的错......

我查询了一些解决方法，并没有起到很好的效果，所以想向您请教

下面是跑running时报的错误：

![image-20220508133452523](https://user-images.githubusercontent.com/95602330/167283559-f9868ed4-a354-4044-aa06-c8f119d2796c.png)

**Comment by ViolinLee** [comment]
> 

大概率是树莓派蓝牙没有设置好，先保证手机能搜索和配对pi的蓝牙

**Comment by XionghuiLi** [comment]
额，手机是可以搜索和配对蓝牙的，
我经过以下尝试：蓝牙关闭running，然后观察报错情况，蓝牙无论关闭与否、连接与否，依旧会报同样的错误。

**Comment by ViolinLee** [comment]
> 额，手机是可以搜索和配对蓝牙的， 我经过以下尝试：蓝牙关闭running，然后观察报错情况，蓝牙无论关闭与否、连接与否，依旧会报同样的错误。

配对成功还需要配置才能通讯，可以参照[这篇文章](https://blog.csdn.net/qq_42747705/article/details/116948131)
