### ISSUE TITLE
国华舵机舵臂螺丝尺寸

### ISSUE THREAD

**Issue by Vincentive1232** [ViolinLee/18_dof_raspberry_pi_hexapod#4]
你好，想请问一下piHexa18的国华舵机的舵臂用的是什么螺丝固定的呢，在对应表里好像找不到对应的

**Comment by ViolinLee** [comment]
> 你好，想请问一下piHexa18的国华舵机的舵臂用的是什么螺丝固定的呢，在对应表里好像找不到对应的

这个没有特定要求，可以用2mm直径6mm长度
